version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverContainer
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssowrd*123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - sqlserver_network
    restart: always

volumes:
  sqlserver_data:

networks:
  sqlserver_network:
    driver: bridge